
export PATH=$PATH:~/.dotfiles/bin
# append to the history file, don't overwrite it
shopt -s histappend

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100000
HISTFILESIZE=200000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

####
# powerline-shell 
####
function _update_ps1() {
    PS1=$(powerline-shell $?)
}

#if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
    #PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
#fi

####
# fzf
###

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

####
# python
####

export PYTHONSTARTUP=~/.dotfiles/python/startup.py

####
# java
####

# Java debugging
export JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"

####
# tmux
####

#Start tmux on every login
[[ $- != *i* ]] && return
[[ -z "$TMUX" ]] && exec tmux

# some more ls aliases
alias ll='ls -alF --color=auto'
alias la='ls -A --color=auto'
alias ls='ls --color=auto'
alias l='ls -CF --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
